---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
spec:
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog
        ports:
        - name: oveinticinco
          containerPort: 8025
        - name: mveinticinco
          containerPort: 1025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
    - name: oveinticinco
      protocol: TCP
      port: 8025
      targetPort: 8025
    - name: mveinticinco
      protocol: TCP
      port: 1025
      targetPort: 1025